name: "PR Notifier"
description: "Notify reviewers and/or authors in Slack when certain events happen in a PR"
inputs:
  slack_bot_token:
    description: "The ID of the slack bot associated with this action"
    required: true
  slack_channel_id:
    description: "The ID of the slack channel that you want the bot to post messages in"
    required: true
  slack_users:
    description: 'This is a JSON stringified array of the users you would like to be able to notify via slack when they are requested to review a PR. The format should be [{ "github_username": string, "slack_id": string }]'
    required: true
    default: "[]"
runs:
  using: "composite"
  steps:
    - run: run.sh
      shell: bash
